### ISSUE TITLE
Add :dev-master to composer install

### ISSUE THREAD

**Issue by ryanglaze-zz** [wardrobecms/wardrobe-archived#1]
Took me a bit to figure out that you have to add :dev-master to the "composer create-project wardrobe/wardrobe" otherwise I was getting an error saying could not find package with stability stable.

**Comment by ghost** [comment]
yes I had to add "--stability=dev" to the composer command to avoid the error

**Comment by laurent-indermuehle** [comment]
Thanks to ryanglaze and seandowney. With --stability=dev it works :)

**Comment by rtablada** [comment]
-s dev is a shorthand.

**Comment by rtablada** [comment]
This should be solved with the 1.0.0 release stable!
