### ISSUE TITLE
Argument 2 passed to Illuminate\\Auth\\Guard::__construct() must be an instance of Illuminate\\Session\\Store

### ISSUE THREAD

**Issue by newtonianb** [wardrobecms/wardrobe-archived#10]
I just tried to setup wardrobe in two different ways.
method 1) `git clone https://github.com/wardrobecms/wardrobe` then `composer install`

method 2) `composer create-project wardrobe/wardrobe`

In both cases before it fully completes I get the following error

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
{"error":{"type":"ErrorException","message":"Argument 2 passed to Illuminate\\Auth\\Guard::__construct() must be an instance of Illuminate\\Session\\Store, instance of Illuminate\\Session\\SessionManager given, called in S:\\PRJ\\wardrobe\\vendor\\wardrob
e\\core\\src\\Wardrobe\\Core\\Facades\\Wardrobe.php on line 62 and defined","file":"S:\\PRJ\\wardrobe\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Guard.php","line":76}}Script php artisan optimize handling the post-install-cmd event returned with an error

[RuntimeException]
Error Output:

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader]
```

this machine is running Windows 8, PHP 5.5, Apache 2

**Comment by alexrussell** [comment]
Almost certainly related to Laravel's change to sessions in https://github.com/laravel/framework/commit/3816e425ae3fdaa69474763737d5e906e073c9a9

**Comment by alexrussell** [comment]
In fact it looks like this was fixed: https://github.com/wardrobecms/core/commit/3a5261ded9c17f77d136cece9a9f8579ca610222 (and https://github.com/wardrobecms/core/issues/56)

Just hasn't hit packagist yet.

**Comment by ericlbarnes** [comment]
Yes I think you need to switch to dev-master in composer or require the earlier version of Laravel. 

At least until I get a new release out.

**Comment by alexrussell** [comment]
I just patched it myself temporarily.

**Comment by ericlbarnes** [comment]
I just update the 1.0 branch so composer update should put everyone up to date.

**Comment by newtonianb** [comment]
thanks so much for the fast turn around, that seems to have fixed it!
