### ISSUE TITLE
typo wardrobe:config

### ISSUE THREAD

**Issue by Viktorminator** [wardrobecms/wardrobe-archived#12]
Small typo in /vendor/wardrobe/core/src/Wardrobe/Core/Console/ConfigCommand.php after installation:

```
protected $name = 'wardrobe:cofig';
```

must be _wardrobe:config_ (I have no idea where to look for wardrobe artisan commands).

**Comment by ericlbarnes** [comment]
This was fixed. #11 I need to update the composer require.
