### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by setkyar** [wardrobecms/wardrobe-archived#13]
I was installing with `composer create-project wardrobe/wardrobe` command. And I gave permission 

`chmod -R 777 app/storage
chmod 777 public/images`

But when I go to `www.mysite.com/public/public/install` I found 404 error.

Any idea how to fix this?

**Comment by ericlbarnes** [comment]
It should be just mysite.com/install as long as you point your vhost to the public dir. Is it redirecting to the double "public" for you or something?

**Comment by ciruz** [comment]
Hi, maybe you haven't enabled mod_rewrite.

If you are not sure, try this url:
http://www.example.com/index.php/install

If you work on your local machine without any vhosts / mod_rewrite, then give this url a try:
http://your-ip-adress/your-wardrobe-path/public/index.php/install

good luck

**Comment by setkyar** [comment]
Yes I already try `http://www.example.com/index.php/install` and `mysite.com/install` but it still doesn't work . But when I install at XAMPP. It was fine. So I try configuration like XAMPP installation but it still have same problem :(

**Comment by ciruz** [comment]
There must be something other wrong. Your vhost configuration is really correct?

Your apache vhost configuration should look like this (to enable mod_rewrite):

``` apache
<VirtualHost *:80>
    ServerAdmin foobar@example.com
    DocumentRoot /your/wardrobe/path/public
    ServerName www.example.com
    ServerAlias example.com
    <Directory /your/wardrobe/path/public>
        Options FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>
```

and you must have a ".htaccess" file in this public directory

``` apache
<IfModule mod_rewrite.c>
    Options -MultiViews
    RewriteEngine On

    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
```

Can you access any other file in your document root?
Create a simple php file in your document root and try to accessing it.

``` php
<?php
phpinfo();
?>
```

Do you get an error 404 when accessing this php file?

PS: Also check your apache error_log :)

**Comment by setkyar** [comment]
Yes Thanks ciruz I was fine now because of I need to configuration `apache vhost`

**Comment by heinafk** [comment]
I think setting 777 isn't a good idea :) it's dangerous. 
chmod -R 777 app/storage
chmod 777 public/images
