### ISSUE TITLE
Validate Tags

### ISSUE THREAD

**Issue by ciruz** [wardrobecms/wardrobe-archived#14]
Please validate if a tag really exists, otherwise show a 404 page.
It's not so cool right now http://goo.gl/qrIrXU :)

thanks guys

**Comment by ericlbarnes** [comment]
whoops :frowning: I'll get this updated.

**Comment by ericlbarnes** [comment]
I just fixed this in the core: https://github.com/wardrobecms/core/commit/8ecebdba9c1f1076b322e82349f75e77b506c625

`composer update` should bring this in for you. 

Thanks for reporting it.
