### ISSUE TITLE
Markdown files

### ISSUE THREAD

**Issue by glockjt** [wardrobecms/wardrobe-archived#18]
Where are the markdown files stored?  I looked in the db at the content column but it is not in markdown form.

**Comment by ericlbarnes** [comment]
It is stored in the posts table content field. If you are not seeing it stored in markdown are you sure you are writing the post in markdown? Markdown parsers support both markdown and html and it should only be storing what you enter into the post form.

**Comment by glockjt** [comment]
Oh ok that answers it, I thought that it always put it into the db with
markdown syntax.  Thanks.
