### ISSUE TITLE
codemirror vs dropzone

### ISSUE THREAD

**Issue by newtonianb** [wardrobecms/wardrobe-archived#19]
I'm a bit confused where exactly is dropzone being used? This whole time I thought the image drop in the text area was dropzone but now I realise it's actually code mirror...

**Comment by ericlbarnes** [comment]
Dropzone is being used in the admin which will allow you drag and drop markdown files to auto create posts. Here is a quick screencast I created back when I added this feature - http://screencast.com/t/DawnI3wMN4XI
