### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by nickdenisenko** [wardrobecms/wardrobe-archived#26]
1. Git clone
2. Composer install
3. PHP Fatal error:  Call to undefined method Illuminate\Foundation\Application::redirectIfTrailingSlash() in /home/user/wardrobe/bootstrap/start.php on line 16

**Comment by ericlbarnes** [comment]
Can you remove line 16 in this file and see if that fixed it?

**Comment by ericlbarnes** [comment]
Fixed in #27

**Comment by nickdenisenko** [comment]
Remove call to redirectIfTrailingSlash in /bootstrap/start.php file.
https://github.com/laravel/laravel/blob/v4.1.0/upgrade.md
