### ISSUE TITLE
Doubly trailing slash

### ISSUE THREAD

**Issue by panoply** [wardrobecms/wardrobe-archived#29]
// double trailing slash makes it impossible to work locally. Any fix using MAMP with this?

**Comment by ericlbarnes** [comment]
Can you be more specific? Where is the double slash? On all urls? some urls? something else?

**Comment by veshinak** [comment]
Hi, Eric! Same trouble:
![double slash](https://cloud.githubusercontent.com/assets/7409631/2845918/df7bbf34-d09b-11e3-9592-571f24ddb00b.png)

**Comment by ericlbarnes** [comment]
This will be fixed in v2. I'm taking all routes out of the composer package and putting them in the base so you'll have full control to adjust as you see fit.
