### ISSUE TITLE
Upgrade Laravel 4.1.26

### ISSUE THREAD

**Issue by ivanlemeshev** [wardrobecms/wardrobe-archived#31]
Make it please http://laravel.com/docs/upgrade

**Comment by Joker666** [comment]
Same problem :(

**Comment by ericlbarnes** [comment]
Require dev-master for wardrobe/core - 
https://github.com/wardrobecms/core/commit/3ba106b389a50f8218050d79cabe646883c6584b

**Comment by Joker666** [comment]
![whoops there was an error](https://cloud.githubusercontent.com/assets/3280322/2902051/812a5398-d5df-11e3-8339-c993230009d1.png)

Though I added the three methodsin 'User' model mentioned in the laravel doc upgrade guide, it didn't work :(

Mybe becozthe CMS is built upon Laravel 4.0
