### ISSUE TITLE
Laravel versions?

### ISSUE THREAD

**Issue by wiiiimm** [wardrobecms/wardrobe-archived#32]
During install, after being asked to add user (/install/user)
I am getting the following error

Class Wardrobe\Core\Models\User contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\Auth\UserInterface::getRememberToken, Illuminate\Auth\UserInterface::setRememberToken, Illuminate\Auth\UserInterface::getRememberTokenName)

This is supposed to be caused by Laravel update from 4.1.25 -> 4.1.26+ http://laravel.com/docs/upgrade#upgrade-4.1.26

See: 
https://github.com/laravel/laravel/commit/f138f0f4fce63fdb371064a66a4c92226a8b1ace

but according to Composer.json, laravel is 4.0.*
and calling php artisan --version, i was told that i am on "Laravel Framework version 4.0.10"

**Comment by wiiiimm** [comment]
I did an install from 
composer create-project wardrobe/wardrobe

it's strange that the composer.json that it came with had

"require": {
        "laravel/framework": "4.0.*",

**Comment by wiiiimm** [comment]
i guess composer version is pointed to an old release (1.0.0) that uses Laravel 4.0.\* and yet references part of wardrobe core that has been updated to use Laravel 4.1.*

**Comment by ericlbarnes** [comment]
I guess this is because after I changed composer on master I didn't tag it. :/ I'll try and get that done today.

**Comment by Djuki** [comment]
@ericbarnes When do you expect to resolve this issue?

**Comment by ericlbarnes** [comment]
Just pushed a tag. I guess it will be a few before it goes out to packagist.
