### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by lifehome** [wardrobecms/wardrobe-archived#41]
Just wondering if this project was dead or somewhat?

**Comment by deadlyhifi** [comment]
Just installed it and now wondering that myself…?

**Comment by mclassic** [comment]
I can only speak for my experience working on this project, so take what I say lightly.

The project is not dead, but it is moving slowly right now. Version 1 has been put on the back burner for now while we start a version 2 based on Laravel 5.

More information may come down the line. Eric is still the project owner and he may have more information down the road, hopefully in the near future.

**Comment by metalmatze** [comment]
Where are you currently talking about features and stuff?!

**Comment by ericlbarnes** [comment]
@MetalMatze We started using IRC #wardrobecms channel.

**Comment by deadlyhifi** [comment]
Good to hear, thanks.

I'll start using it and then perhaps get involved on the v2…
