### ISSUE TITLE
Installation instructions failed

### ISSUE THREAD

**Issue by grancier** [wardrobecms/wardrobe-archived#43]
Hi.

I tried to install wardrobe via composer as indicated on your install section, but it didn't work, the install failed saying Class 'Patchwork\Utf8\Bootup' not found in autoload.php

I tried clearing autoload.php and doing composer install but it didn't work

What I ended up doing was installing Laravel 4.1 from scratch:
 composer create-project laravel/laravel wardrobe 4.1 --prefer-dist

The installing patchwork utf8:
composer require patchwork/utf8 1.1.x-dev

Then installing  wardrobe core
composer require wardrobe/core

And then bringing in the Wardrobe files from git.

Then I was able to set up wardrobe and install a user.

But once I got it installed I couldn't access the login page. I had to add the login routes from core::routes.admin_group_rules to core::routes.blog_group_rules 

Maybe you guys need to update the instructions and the code a bit.

Thanks.

**Comment by ciruz** [comment]
I'm pretty sure Wardrobe is not in active development anymore, @ericbarnes also worked on a v2 a year ago (https://github.com/wardrobecms/v2).

**Comment by ericlbarnes** [comment]
😦 yeah, not sure when I'll have the time or energy to put forth on this. Sorry.
