### ISSUE TITLE
can not create-project wardrobe/wardrobe

### ISSUE THREAD

**Issue by liweihan** [wardrobecms/wardrobe-archived#5]
getting an error of
Could not find package wardrobe/wardrobe with stability stable.

**Comment by rtablada** [comment]
Already addressed in #1

**Comment by ericlbarnes** [comment]
I just updated the docs as well. 
http://wardrobecms.com/docs/installation

## 

Eric Barnes

On August 27, 2013 at 4:48:24 PM, Ryan Tablada (notifications@github.com) wrote:

Already addressed in #1
