### ISSUE TITLE
Can we use wardrobe on mainstream hosting ?

### ISSUE THREAD

**Issue by ghost** [wardrobecms/wardrobe-archived#7]
First, it's the first time I try to use a project which need Composer. And I'm not sure how to handle it.

I sent complete wardrobe directory by FTP on a mainstream web hosting (in my case, OVH) and modified the database file. But, what should I do with Composer since I don't want to use Wardrobe locally, but on the web host.

Can you guide me to the right spot ?

Kind,

**Comment by ericlbarnes** [comment]
Hi,

Can you post this in the forum? - http://wardrobecms.com/forum

This isn't really an issue just more of a "best practice" type question.
